### PR TITLE
feature: Add output file name

### PR DESCRIPTION
**Pull request by javix64**
After some hours of checking the code and do some "trial-error", finally I can say that it is working.

Please check the files edited and make the appropriate changes.

### CODE REVIEW

**Comment by javix64** [comment]
Yesterday, I forget to comment:
Please check the test that I have edited yesterday, because I did not do much tests before, probably I fake it, but not idea tbh.

I did the test with the option of: '--name', but I did not the test without that option. Today I checked and it was retrieving the name: `undefined.es.json`. I have fixed with a ternary operator inside the `json_file.ts`.

Something that probably we need to check:
- `cli/cli.ts`: I do not know if the new option --name it is marked as optional with `[string]`.
- `utils/prompt.ts`: I have add the option to the prompt, but I do not know if it is "clean".
- I did not do the test with the package usage. Probably we do not need to do it, as this feature was concerning only CLI usage.

Please, check it and tell me if I can do it better :smiley: .

**Comment by ParvinEyvazov** [comment]
hey @javix64, you are the king!

Looks good for now. I will merge it and test it. After a successful test, will publish a new release.

Thank you!

**Comment by javix64** [comment]
always glad to help! 😄

**Comment by ParvinEyvazov** [comment]
Hey @javix64 ,

Finally, I could a time to do a full test. After a bunch of quick fixes, I released your latest changes. Now [jsontt v1.9.0](https://www.npmjs.com/package/@parvineyvazov/json-translator) has an `--name` output name feature. 

Thank you for your contribution. 💪

**Pull request merged**
