### PR TITLE
feat: add DeepL translator

### PR DESCRIPTION
**Pull request by rrmdn**
I thought this might be helpful for others, as it was for me.

- Translate JSON using DeepL API
- Reads DeepL API key from `process.env.DEEPL_API_KEY`

### CODE REVIEW

**Comment by ParvinEyvazov** [comment]
Great job @rrmdn! 😍

Currently there is a bug on main about output file name. I will merge & release this feature after solving that bug.

Thank you!

**Comment by ParvinEyvazov** [comment]
@rrmdn  Can you please remove package-lock.json and use yarn?

**Comment by rrmdn** [comment]
> @rrmdn Can you please remove package-lock.json and use yarn?

Yes, on it

**Comment by ParvinEyvazov** [comment]
Hi @rrmdn ,

I am working on some structure changes. I am planning to merge this soon! Thank you for your patience.

**Comment by ParvinEyvazov** [comment]
Merged! Thank you for contribution @rrmdn.

I will adapt changes to the new structure and publish it soon.

**Pull request merged**
